export const mainTypes = {
    SAVE_CURRENT_CHARACTER: 'SAVE_CURRENT_CHARACTER',
    ADD_RIGHT_ANSWER: 'ADD_RIGHT_ANSWER',
    ADD_WRONG_ANSWER: 'ADD_WRONG_ANSWER',
    DELETE_RESULTS: 'DELETE_RESULTS',
}